apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.image.name }}-config
  labels:
    app: {{ .Values.image.name }}
data:
  config.yaml: {{ required "A valid .Values.config entry is required!" (toYaml .Values.config | indent 2) }}
