apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: {{ .Values.containerPort | quote }}
    prometheus.io/scrape: "true"
  name: {{ .Values.image.name }}-svc
  labels:
    app: {{ .Values.image.name }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.image.name }}
  type: ClusterIP
